AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  moralpain

  SAM Template for moralpain

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      OpenApiVersion: 3.0.1
      StageName: v1
      DefinitionUri: api.yaml

  SubmitSurveyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: SubmitSurvey
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.UniqueKeyUploader::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          bucket: moralpain-submissions
          prefix: surveys
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_submit_survey_role
      Events:
        Get:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /survey
            Method: post
            ApiId: !Ref ApiGatewayApi

  SubmitVisitedResiliencyResourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SubmitVisitedResiliencyResources
      CodeUri: MoralPainFunctions
      Handler: edu.uva.cs.moralpain.s3.UniqueKeyUploader::handleRequest
      Runtime: java8.al2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          bucket: moralpain-submissions
          prefix: resiliency
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda_submit_visited_resources_role
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /resiliency
            Method: post
            ApiId: !Ref ApiGatewayApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SubimitSurveyFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for SubmitSurvey function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/v1/survey/"
  SubmitSurveyFunction:
    Description: "SubmitSurvey Lambda Function ARN"
    Value: !GetAtt SubmitSurveyFunction.Arn
  SubmitVisitedResiliencyResourcesFunctionAPI:
    Description: "API Gateway endpoint URL for Prod stage for SubmitVisitedResiliencyResources function"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/v1/ResiliencyResources/"
  SubmitVisitedResiliencyResourcesFunction:
    Description: "SubmitVisitedResiliencyResources Lambda Function ARN"
    Value: !GetAtt SubmitVisitedResiliencyResourcesFunction.Arn
