/*
 * MoralDistress API
 * MoralDistress API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Icon
 */
public class IconTest {
    private final Icon model = new Icon();

    /**
     * Model tests for Icon
     */
    @Test
    public void testIcon() {
        // TODO: test Icon
    }

    /**
     * Test the property 'codePoint'
     */
    @Test
    public void codePointTest() {
        // TODO: test codePoint
    }

    /**
     * Test the property 'fontFamily'
     */
    @Test
    public void fontFamilyTest() {
        // TODO: test fontFamily
    }

    /**
     * Test the property 'fontPackage'
     */
    @Test
    public void fontPackageTest() {
        // TODO: test fontPackage
    }

}
