/*
 * MoralDistress API
 * MoralDistress API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Icon
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-03T18:52:51.342920Z[Etc/UTC]")
public class Icon {
  public static final String SERIALIZED_NAME_CODE_POINT = "codePoint";
  @SerializedName(SERIALIZED_NAME_CODE_POINT)
  private String codePoint;

  public static final String SERIALIZED_NAME_FONT_FAMILY = "fontFamily";
  @SerializedName(SERIALIZED_NAME_FONT_FAMILY)
  private String fontFamily;

  public static final String SERIALIZED_NAME_FONT_PACKAGE = "fontPackage";
  @SerializedName(SERIALIZED_NAME_FONT_PACKAGE)
  private String fontPackage;

  public Icon() { 
  }

  public Icon codePoint(String codePoint) {
    
    this.codePoint = codePoint;
    return this;
  }

   /**
   * Get codePoint
   * @return codePoint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCodePoint() {
    return codePoint;
  }


  public void setCodePoint(String codePoint) {
    this.codePoint = codePoint;
  }


  public Icon fontFamily(String fontFamily) {
    
    this.fontFamily = fontFamily;
    return this;
  }

   /**
   * Get fontFamily
   * @return fontFamily
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFontFamily() {
    return fontFamily;
  }


  public void setFontFamily(String fontFamily) {
    this.fontFamily = fontFamily;
  }


  public Icon fontPackage(String fontPackage) {
    
    this.fontPackage = fontPackage;
    return this;
  }

   /**
   * Get fontPackage
   * @return fontPackage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFontPackage() {
    return fontPackage;
  }


  public void setFontPackage(String fontPackage) {
    this.fontPackage = fontPackage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Icon icon = (Icon) o;
    return Objects.equals(this.codePoint, icon.codePoint) &&
        Objects.equals(this.fontFamily, icon.fontFamily) &&
        Objects.equals(this.fontPackage, icon.fontPackage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codePoint, fontFamily, fontPackage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Icon {\n");
    sb.append("    codePoint: ").append(toIndentedString(codePoint)).append("\n");
    sb.append("    fontFamily: ").append(toIndentedString(fontFamily)).append("\n");
    sb.append("    fontPackage: ").append(toIndentedString(fontPackage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("codePoint");
    openapiFields.add("fontFamily");
    openapiFields.add("fontPackage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Icon
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (Icon.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in Icon is not found in the empty JSON string", Icon.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!Icon.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Icon` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("codePoint") != null && !jsonObj.get("codePoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `codePoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("codePoint").toString()));
      }
      if (jsonObj.get("fontFamily") != null && !jsonObj.get("fontFamily").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fontFamily` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fontFamily").toString()));
      }
      if (jsonObj.get("fontPackage") != null && !jsonObj.get("fontPackage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fontPackage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fontPackage").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Icon.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Icon' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Icon> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Icon.class));

       return (TypeAdapter<T>) new TypeAdapter<Icon>() {
           @Override
           public void write(JsonWriter out, Icon value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Icon read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Icon given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Icon
  * @throws IOException if the JSON string is invalid with respect to Icon
  */
  public static Icon fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Icon.class);
  }

 /**
  * Convert an instance of Icon to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

