name: Publish to GitHub Pages

on:
  push:
    branches: 
      - main
      - webpage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'
      - run: |
          echo "building api dependency..."
          cd api/dart
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: moraldistress
          webRenderer: canvaskit
          baseHref: /moralpain_dev/
