/*
 * MoralDistress API
 * MoralDistress API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AnalyticsResult;
import org.openapitools.client.model.Submissions;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminApi
 */
@Ignore
public class AdminApiTest {

    private final AdminApi api = new AdminApi();

    /**
     * Get data analysis
     *
     * Perform an analysis on the records in the database that match the query paramters. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAnalyticsTest() throws ApiException {
        String operation = null;
        Integer starttime = null;
        Integer endtime = null;
        AnalyticsResult response = api.getAnalytics(operation, starttime, endtime);

        // TODO: test validations
    }
    /**
     * Get survey results
     *
     * Fetch from the database all of the records that match the query parameters. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSubmissionsTest() throws ApiException {
        Integer starttime = null;
        Integer endtime = null;
        Integer minscore = null;
        Integer maxscore = null;
        Submissions response = api.getSubmissions(starttime, endtime, minscore, maxscore);

        // TODO: test validations
    }
}
